<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{f351573f-96fa-47a5-8ea4-1d431a423779}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Axis1: AXIS_REF;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>